version: "2"
services:
  web:
    build: .
    ports:
    - "4000:4000"
    volumes:
    - ".:/app/"
    links:
    - postgres:postgres
    env_file: .env
  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
